[20:40:57] I/launcher - Running 1 instances of WebDriver
[20:40:57] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
null
test_step_inputadmin
test_step_inputadmin1
test_step_click Number of Attempts Left: 5
test_step_click Login
test_step_click   Glossary
test_step_click Variable Impact Report
presence
xpath in same page
assert Variable Impact Report
[31mF[0m

Failures:
1) java navigation5
  Message:
[31m    Failed: No element found using locator: By(xpath, /html/body/app-root/app-layout/section/app-impact/div[1]/app-page-header/div/div/ol/li[2])[0m
  Stack:
    NoSuchElementError: No element found using locator: By(xpath, /html/body/app-root/app-layout/section/app-impact/div[1]/app-page-header/div/div/ol/li[2])
        at C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27
        at ManagedPromise.invokeCallback_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
        at C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
        at processTicksAndRejections (node:internal/process/task_queues:96:5)Error
        at ElementArrayFinder.applyAction_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
        at ElementArrayFinder.<computed> [as getText] (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
        at ElementFinder.<computed> [as getText] (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
        at D:\iTAP\Recorded_Scenarios\java\navigation5\spec.js:260:112
        at ManagedPromise.invokeCallback_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
        at C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    From: Task: Run it("navigation5") in control flow
        at UserContext.<anonymous> (C:\Users\sv00810785\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (D:\iTAP\Recorded_Scenarios\java\navigation5\spec.js:8:21)
        at Object.<anonymous> (D:\iTAP\Recorded_Scenarios\java\navigation5\spec.js:7:15)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)

1 spec, 1 failure
Finished in 48.921 seconds

[20:41:52] I/launcher - 0 instance(s) of WebDriver still running
[20:41:52] I/launcher - chrome #01 failed 1 test(s)
[20:41:52] I/launcher - overall: 1 failed spec(s)
[20:41:52] E/launcher - Process exited with error code 1
